name: nestjs todo api Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  test:
    name: Install & run & test & build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: check node
        run: node -v && pwd && ls

      - name: Install yarn
        run: npm install --global yarn && yarn -v

      - name: install depenses using yarn
        run: yarn

      - name: run tests
        run: yarn test

      - name: run build
        run: yarn build
