name: Docker Image CI

on:
  push:
    branches: ['master']
#   pull_request:
#     branches: ['master']

# jobs:
#   test:
#     name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         node_version: ['16']
#         os: [ubuntu-latest, windows-latest, macOS-latest]

#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js ${{ matrix.node_version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node_version }}

#       - name: npm install, build and test
#         run: |
#           npm install
#           echo "Done!!!"

jobs:
  test:
    name: Testing things
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: check node
        run: node -v

      - name: Install yarn
        run: npm install --global yarn && yarn -v

      - name: install depenses using yarn
        run: yarn

      - name: run tests
        run: yarn test
